// scaler_coeffs_v.v — V-filter coefficient ROM, 4 taps × 64 phases.
// Loads from scaler_coeffs_v.hex (generated by python/gen_coeffs.py).
// Signed Q1.11 (12 bits two's complement) coefficients.

`default_nettype none
`timescale 1ns / 1ps

module scaler_coeffs_v (
    input  wire [5:0]   phase,        // 0..63
    // Flat 48-bit bus = 4 × 12-bit signed, tap 0 in LSBs, tap 3 in MSBs.
    output wire [47:0]  taps_flat
);
    // 64 phases × 4 taps = 256 entries × 12 bits
    reg [11:0] rom [0:255];
    initial $readmemh("scaler_coeffs_v.hex", rom);

    assign taps_flat = {
        rom[{phase, 2'd3}],
        rom[{phase, 2'd2}],
        rom[{phase, 2'd1}],
        rom[{phase, 2'd0}]
    };
endmodule

`default_nettype wire
