// scaler_coeffs_h.v — H-filter coefficient ROM, 8 taps × 64 phases.
// Loads from scaler_coeffs_h.hex (generated by python/gen_coeffs.py).
// Signed Q1.11 (12 bits two's complement) coefficients.
// Combinational output: pack 8 taps for the current phase into one wide bus.

`default_nettype none
`timescale 1ns / 1ps

module scaler_coeffs_h (
    input  wire [5:0]   phase,        // 0..63
    // Flat 96-bit bus = 8 × 12-bit signed, tap 0 in LSBs, tap 7 in MSBs.
    output wire [95:0]  taps_flat
);
    // 64 phases × 8 taps = 512 entries × 12 bits
    reg [11:0] rom [0:511];
    initial $readmemh("scaler_coeffs_h.hex", rom);

    assign taps_flat = {
        rom[{phase, 3'd7}],
        rom[{phase, 3'd6}],
        rom[{phase, 3'd5}],
        rom[{phase, 3'd4}],
        rom[{phase, 3'd3}],
        rom[{phase, 3'd2}],
        rom[{phase, 3'd1}],
        rom[{phase, 3'd0}]
    };
endmodule

`default_nettype wire
